# Generated by Django 3.0.3 on 2020-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_auto_20200410_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid_ind',
            name='active',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid_ind',
            name='confirmed',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid_ind',
            name='day_increment_active',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid_ind',
            name='day_increment_confirmed',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid_ind',
            name='day_increment_deaths',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid_ind',
            name='day_increment_recovered',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid_ind',
            name='deaths',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid_ind',
            name='recovered',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
