# Generated by Django 3.0.3 on 2020-04-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0003_auto_20200410_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_data_anal',
            name='cumulative_death',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='covid_data_anal',
            name='cumulative_recov',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='covid_data_anal',
            name='daily_data',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='covid_data_anal',
            name='daily_death',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='covid_data_anal',
            name='daily_recov',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='covid_data_anal',
            name='state_wise',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
    ]
