# Generated by Django 3.0.3 on 2020-04-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0004_auto_20200410_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid_data_anal',
            old_name='cumulative_conf',
            new_name='age_distribution',
        ),
        migrations.RenameField(
            model_name='covid_data_anal',
            old_name='cumulative_death',
            new_name='daily_confirm',
        ),
        migrations.RenameField(
            model_name='covid_data_anal',
            old_name='cumulative_recov',
            new_name='daily_decease',
        ),
        migrations.RenameField(
            model_name='covid_data_anal',
            old_name='daily_data',
            new_name='daily_hospitalize',
        ),
        migrations.RenameField(
            model_name='covid_data_anal',
            old_name='daily_death',
            new_name='monthly_confirm',
        ),
        migrations.RemoveField(
            model_name='covid_data_anal',
            name='state_wise',
        ),
    ]
